Rm/lr state request
TuiChain/backend pull request #43
Opened 2021-01-05 21:37 UTC by ricardomilhazes

2021-01-05 22:00 UTC, ricardofsc10 reviewed
Nice job mate.

2021-01-05 22:01 UTC, ricardofsc10 approved these changes

2021-01-06 03:56 UTC, mrr37 approved these changes

2021-01-06 10:20 UTC, hpereira98 requested changes

2021-01-06 10:20 UTC, hpereira98 commented on tuichain/api/views/loanrequests.py
> +def get_specific_state_loan_requests(request, status):
I think every user should be able to do this, with some restrictions:
- pending, cancelled and finished and expired can only be seen by the user that requested the loans
- active should be seen by the users that requested it or invested on it
- funding can be seen by everyone

2021-01-07 10:04 UTC, hpereira98 approved these changes

2021-01-07 16:01 UTC, merged